### ISSUE TITLE
Please enable Wayland

### ISSUE THREAD

**Issue by uncomfyhalomacro** [ungoogled-software/ungoogled-chromium-flatpak#1]
Hello! Love that its now a verified flathub app. I just have a single request, can this build enable Wayland through ozone platform? Before it was verified, it can check the environment automatically which is quite nice.

I understand if it isn't high priority!

**Comment by sambonbonne** [comment]
I would like this too: I use Gnome with fractional scaling and before the change, I could setup the Ozone platform to Wayland and it fixed the blurry text I have on Chromium.
But since the change, the Ozone platform is set to Wayland but I have the blurry text back.

**Comment by rany2** [comment]
Are you sure this issue still exists? Wayland works fine for me but it's not enabled by default.

**Comment by rany2** [comment]
@sambonbonne The thing is, it works fine for me. This is my `chromium-flags.conf`:

```
# cat ~/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium-flags.conf 
--gtk-version=4
--ozone-platform-hint=wayland
features+=UseOzonePlatform
features+=TouchpadOverscrollHistoryNavigation
```

**Comment by sambonbonne** [comment]
@rany2 using the same `chromium-flags.conf` as you fixes the problem but I didn't have this file before and it was working perfectly, so it may be a regression.

**Comment by rany2** [comment]
@sambonbonne it's a known issue and bug in Chromium, setting it from `chrome://flags` doesn't work

**Comment by sambonbonne** [comment]
@rany2 it was working before the package transition, so I don't understand why it doesn't work anymore.

**Comment by rany2** [comment]
@sambonbonne it's a coincidence that the Chromium update and transition happened at the same time, the manifest is identical :)

**Comment by uncomfyhalomacro** [comment]
Hello. Thanks for the clarification. Yes. It's kinda weird that it fixed itself lmao. Thanks again for this wonderful project!
