### ISSUE TITLE
Cannot add search engines

### ISSUE THREAD

**Issue by vovchykbratyk** [ungoogled-software/ungoogled-chromium-flatpak#2]
I'm using flatpak (version 124.0.6367.118) on Debian (aarch64, VM on MacOS host), and cannot add search engines.

I've enabled NeverDecaf's `chromium-web-store` extension.

Installed Startpage extension - no errors thrown.

However, I am unable to search Startpage from the omnibox.

When I go into chrome://settings/searchEngines, there is no option to add any new search engines (see below image - I could remove Bing/Yahoo/Yandex, but I cannot add anything).
<img width="676" alt="Screenshot 2024-05-07 at 09 22 08" src="https://github.com/ungoogled-software/ungoogled-chromium-flatpak/assets/40668075/577d6d11-e3c9-4614-b129-207507523874">

I can add a shortcut, but that is not the desired behavior.  On MacOS (arm64) ungoogled-chromium (installed via homebrew), the process above results in startpage being added as a search option, and searching via custom search engine from the omnibox functions as designed.

**Comment by rany2** [comment]
You should be able to add a search engine via "Site search" and if a site supports OpenSearch than Chromium will automatically populate it as a "search engine."
