### ISSUE TITLE
Can't download any files

### ISSUE THREAD

**Issue by Mites-G** [ungoogled-software/ungoogled-chromium-flatpak#8]
Since a couple days ago, I have not been able to download any files through Ungoogled Chromium flatpak version.
     
I've installed the regular `chromium` from flatpak and that does download files normally.
I have no idea how to debug this issue, so instructions on how to get to the logs and whatnot would be greatly appreciated.
    
System: Arch KDE Plasma
     
Steps to reproduce:
     
1 - attempt to download any file or picture from any website
2 - select the destination directory
3 - press `CTRL+J` to go to the downloads page
4 - notice your file hasnt appeared there
5 - navigate manually to your folder
6 - notice your file isn't there also

**Comment by rfernandez-neoris** [comment]
How did you solve this?

**Comment by Mites-G** [comment]
> How did you solve this?

I wasn't able to solve this, just moved on to another browser
