### ISSUE TITLE
Where to specify a kerberos-related policy?

### ISSUE THREAD

**Issue by bocekm** [ungoogled-software/ungoogled-chromium-flatpak#9]
Hi. Following https://github.com/flathub/com.github.Eloston.UngoogledChromium/issues/56#issuecomment-1112239489 I wanted to set the `DisableAuthNegotiateCnameLookup` policy in ~/.var/app/io.github.ungoogled_software.ungoogled_chromium/config/chromium-flags.conf but then I found out that there's no command line switch `--disable-auth-negotiate-cname-lookup` anymore. It was removed under https://codereview.chromium.org/832423004/.

In which folder can I place the policy json file so that it's picked up by the flatpak version of the ungoogled chromium on Fedora 40?

**Comment by bocekm** [comment]
Ok, I found https://github.com/ungoogled-software/ungoogled-chromium-flatpak?tab=readme-ov-file#extension-points but I'm unsure what exactly to do.

I've created a `/var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.kerberos/` folder and put `io.github.ungoogled_software.ungoogled_chromium.Policy.kerberos.yaml` and `kerberos.json` in it.

What do you mean by:
> with /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.system-policies/<arch>/<version> being a symlink to /etc/chromium-browser

Shall I create a `/var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.kerberos/x86_64/1` folder and what should I symlink it to?

**Comment by rany2** [comment]
@bocekm If you installed UGC as a system installation, replace `--user` with `--system`. In short, this should work:

```
cd examples/policies/block-dinosaur-game
flatpak-builder --install --user --force-clean _build io.github.ungoogled_software.ungoogled_chromium.Extension.block-dinosaur-game.yaml
```

**Comment by andrew-ma** [comment]
Alternatively you can use the Policy Extension Point without building a separate flatpak:


######################################################


# If "Ungoogled Chromium" Flatpak, use custom Chrome policy by running:

## (LOCKED POLICY SETTINGS)
```
sudo -i
mkdir -p /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.system-policies/x86_64/1/policies/managed/;
find /var/lib/flatpak/extension -type d -exec chmod 0755 {} \;

cp <PATH_TO_CUSTOM_POLICY_JSON> /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.system-policies/x86_64/1/policies/managed/managed_chrome_132_policy.json;

chmod 0444 /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.system-policies/x86_64/1/policies/managed/managed_chrome_132_policy.json;
```


## (USER-CHANGEABLE DEFAULT POLICY SETTINGS)
```
sudo -i
mkdir -p /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.system-policies/x86_64/1/policies/recommended/;
find /var/lib/flatpak/extension -type d -exec chmod 0755 {} \;

cp <PATH_TO_CUSTOM_POLICY_JSON> /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.system-policies/x86_64/1/policies/recommended/recommended_chrome_132_policy.json;

chmod 0444 /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.system-policies/x86_64/1/policies/recommended/recommended_chrome_132_policy.json;
```


######################################################


# If "Chromium" Flatpak, use custom Chrome policy by running:

## (LOCKED POLICY SETTINGS)
```
sudo -i
mkdir -p /var/lib/flatpak/extension/org.chromium.Chromium.Policy.system-policies/x86_64/1/policies/managed/;
find /var/lib/flatpak/extension -type d -exec chmod 0755 {} \;

cp <PATH_TO_CUSTOM_POLICY_JSON> /var/lib/flatpak/extension/org.chromium.Chromium.Policy.system-policies/x86_64/1/policies/managed/managed_chrome_132_policy.json;

chmod 0444 /var/lib/flatpak/extension/org.chromium.Chromium.Policy.system-policies/x86_64/1/policies/managed/managed_chrome_132_policy.json;
```


## (USER-CHANGEABLE DEFAULT POLICY SETTINGS)
```
sudo -i
mkdir -p /var/lib/flatpak/extension/org.chromium.Chromium.Policy.system-policies/x86_64/1/policies/recommended/;
find /var/lib/flatpak/extension -type d -exec chmod 0755 {} \;

cp <PATH_TO_CUSTOM_POLICY_JSON> /var/lib/flatpak/extension/org.chromium.Chromium.Policy.system-policies/x86_64/1/policies/recommended/recommended_chrome_132_policy.json;

chmod 0444 /var/lib/flatpak/extension/org.chromium.Chromium.Policy.system-policies/x86_64/1/policies/recommended/recommended_chrome_132_policy.json;
```

**Comment by bocekm** [comment]
Hi folks, after updating ungoogled-chrome recently, I had to recreate the extension as it depended on an old freedesktop.org SDK 23.08. I've used 25.08 in the extension yaml, but it doesn't work anymore. I've tried the @andrew-ma's USER-CHANGEABLE DEFAULT POLICY SETTINGS approach but that doesn't work either. Do you know what might have changed?

**Comment by bocekm** [comment]
This is the content of my extension yaml:
```
$ cat /var/lib/flatpak/extension/io.github.ungoogled_software.ungoogled_chromium.Policy.kerberos/io.github.ungoogled_software.ungoogled_chromium.Policy.kerberos.yaml
app-id: io.github.ungoogled_software.ungoogled_chromium.Policy.kerberos
# This should match the extension point version
branch: '1'
runtime: io.github.ungoogled_software.ungoogled_chromium
runtime-version: stable
sdk: org.freedesktop.Sdk//25.08
build-extension: true
appstream-compose: false

modules:
  - name: policy
    buildsystem: simple
    build-commands:
      - mkdir -p ${FLATPAK_DEST}/policies/managed
      - install -Dm 644 kerberos.json ${FLATPAK_DEST}/policies/managed
    sources:
      - type: file
        path: kerberos.json
```
